version: '2'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: edefpr
      MYSQL_DATABASE: edef_pr
    ports:
      - "8889:3306"

  backend:
    build:
      context: ./backend/
    command: php artisan serve --host=0.0.0.0
    volumes:
      - ./backend/:/usr/app/backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env.docker # auto-load .env file!
    links:
      - db
  
  frontend:
    build:
      context: ./frontend/
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./frontend/:/usr/app/frontend
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "8080:80"
