version: '2'

services:
  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: ./mariadb/.env
    ports:
      - "8889:3306"

  backend:
    build:
      context: ./backend/
    command: php artisan serve --host=0.0.0.0
    volumes:
      - ./backend/:/usr/app/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file: ./backend/.env.docker
    links:
      - mariadb
  
  frontend:
    build:
      context: ./frontend/
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./frontend/:/usr/app/frontend
      - /usr/app/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    ports:
      - "443:443"
    expose:
      - "443"
