version: '2'
services:
  backend:
    build:
      context: ./backend/
    command: yarn start
    # command: /usr/app/node_modules/.bin/nodemon ./src/app
    volumes:
      - ./backend/:/usr/app/backend
      - /usr/app/backend/node_modules
    ports:
      - "3000:3000"
    # env_file: ./backend/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  frontend:
    build:
      context: ./frontend/
    command: yarn build start
    volumes:
      - ./frontend/:/usr/app/frontend
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3001:3001"